Implement Back4App Integration and Topic-Based User Matching for Chat
MichelMeyer19/whisperweb pull request #26
Opened 2023-11-23 16:03 UTC by aywebe

Implemented Back4App backend integration to facilitate user login processes. Enhanced the platform by introducing a feature that allows users to select conversation topics for matching purposes; these preferences are now maintained in the backend, setting the stage for upcoming chat functionalities. Ongoing efforts are focused on developing the chat system, which aims to pair users based on shared topic interests and generate a unique chat ID for each successful match.

2023-11-30 11:43 UTC, igawaclawska commented on src/components/atoms/LogoutFunction.jsx
> +  }
Is the Button responsible for the Log-Out process? 
What do you think of this approach, @mircealungu ?

2023-11-30 11:53 UTC, igawaclawska commented on src/components/molecules/FieldMolecule.jsx
> +const FieldMolecule = ({
Rename with `Field`

2023-11-30 11:56 UTC, igawaclawska commented on src/components/pages/NewChat.jsx
> +  // function to retreive topics and create list of dictionaries (incl. topic_id and topic_name)
Nice that you have added comments to your code! :)

2023-11-30 12:06 UTC, igawaclawska requested changes
Good job overall!
I have added a few comments. Take a look at them and apply changes you agree with. Let us know in the comments once you are done.

iga and @mircealungu

2023-12-04 09:36 UTC, aywebe commented on src/components/molecules/FieldMolecule.jsx
> +const FieldMolecule = ({
Done :)

2023-12-04 09:37 UTC, aywebe commented on src/components/organisms/AuthFormOrganism.jsx
> +  onSubmit, // Function to execute on form submission
Done :)

2023-12-05 06:42 UTC, igawaclawska approved these changes

2023-12-05 10:41 UTC, merged